# Generated by Django 5.2.14 on 2026-07-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
