# Generated by Django 5.2.14 on 2026-07-06 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='appointment_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='assigned_technician_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='issue',
            name='feedback_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('WATER', 'Water'), ('ELECTRICITY', 'Electricity'), ('SANITATION', 'Waste'), ('ROAD', 'Roads'), ('SECURITY', 'Security'), ('LIGHTING', 'Lighting'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
