# Generated by Django 5.2.14 on 2026-07-06 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizens', '0002_citizen_rejection_reason'),
        ('notifications', '0003_smslog_direction_smslog_issue_smslog_logged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_citizen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='citizens.citizen'),
        ),
    ]
